
version: '3.8'

services:
  cloudflare-navigator-backend:
    image: jsrankit/dns-cloudflare:latest
    container_name: ENDUSERCOMPUTE_BE_CLOUDFLARE
    ports:
      - "${PORT:-3001}:${PORT:-3001}"  # Expose backend API port
    restart: always
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-https://api.cloudflare.com/client/v4}
      - PORT=${PORT:-3001}
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3001}/api/cloudflare/test-connection"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - cloudflare_net
  
  cloudflare-navigator-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ENDUSERCOMPUTE_FE_CLOUDFLARE
    ports:
      - "8080:8080"  # Expose frontend port
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    driver: bridge
