
version: '3.8'

services:
  cloudflare-navigator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL:-https://api-cloudflare.endusercompute.in}
    ports:
      - "${FRONTEND_PORT:-8080}:8080"  # Frontend
      - "${BACKEND_PORT:-3001}:3001"  # Backend API
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-https://api-cloudflare.endusercompute.in}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
      - PORT=${BACKEND_PORT:-3001}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - /app/node_modules
