
version: '3.8'

services:
  cloudflare-navigator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Frontend
      - "3001:3001"  # Backend API
    restart: unless-stopped
    environment:
      - NODE_ENV=production
