version: '3.8'

services:
  backend:
    build: ./BE
    ports:
      - "3001:3001"
      - "3443:3443"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - API_URL=https://api.cloudflare.com/client/v4
      - SSL_ENABLED=false
      - SSL_CERT_PATH=/app/ssl/cert.pem
      - SSL_KEY_PATH=/app/ssl/key.pem
      - SSL_PORT=3443
    volumes:
      - ./ssl:/app/ssl:ro
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./FE
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - PORT=8080
      - SSL_ENABLED=false
      - SSL_CERT_PATH=/app/ssl/cert.pem
      - SSL_KEY_PATH=/app/ssl/key.pem
      - SSL_PORT=8443
    volumes:
      - ./ssl:/app/ssl:ro
      - ./version.json:/app/dist/version.json:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ssl-certs:
    driver: local