
services:
  frontend:
    build:
      context: .
      dockerfile: FE/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - PORT=8080
      - BACKEND_SERVICE_URL=http://backend:3001/
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
