
services:
  frontend:
    build:
      context: .
      dockerfile: FE/Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    depends_on:
      - backend
    environment:
      - PORT=8080
      - BACKEND_SERVICE_URL=http://backend:${BACKEND_PORT:-3001}/
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
