
version: '3.8'

services:
  cloudflare-navigator:
    image: jsrankit/dns-cloudflare:latest
    container_name: ENDUSERCOMPUTE_FE_CLOUDFLARE
    ports:
      - "${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}"  # Frontend
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"  # Backend API
    restart: always
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-https://api.cloudflare.com/client/v4}
      - FRONTEND_URL=${FRONTEND_URL:-https://localhost:3001}
      - BACKEND_URL=${BACKEND_URL:-https://localhost:3000}
      - PORT=${BACKEND_PORT:-3000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3001}
      - BACKEND_PORT=${BACKEND_PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:${FRONTEND_PORT:-3001}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    driver: bridge
