services:
  backend:
    image: jsrankit/cdm-server:latest
    container_name: cloudflare-navigator-tool-API
    pull_policy: always
    ports:
      - "3001:3001"
      - "3443:3443"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - API_URL=https://api.cloudflare.com/client/v4
      - SSL_ENABLED=true
      - SSL_CERT_PATH=/app/ssl/fullchain1.pem
      - SSL_KEY_PATH=/app/ssl/privkey1.pem
      - SSL_PORT=3443
    volumes:
      - /home/pi/Downloads/fullchain1.pem:/app/ssl/fullchain1.pem:ro
      - /home/pi/Downloads/privkey1.pem:/app/ssl/privkey1.pem:ro
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: jsrankit/cdm-ui:latest
    container_name: cloudflare-navigator-tool-UI
    pull_policy: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - PORT=8080
      - SSL_ENABLED=true
      - SSL_CERT_PATH=/app/ssl/fullchain1.pem
      - SSL_KEY_PATH=/app/ssl/privkey1.pem
      - SSL_PORT=8443
    volumes:
      - /home/pi/Downloads/fullchain1.pem:/app/ssl/fullchain1.pem:ro
      - /home/pi/Downloads/privkey1.pem:/app/ssl/privkey1.pem:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
