services:
  frontend:
    build:
      context: .
      dockerfile: FE/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001

  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production