
version: '3.8'

services:
  cloudflare-navigator:
    image: jsrankit/dns-cloudflare:latest
    container_name: ENDUSERCOMPUTE_FE_CLOUDFLARE
    ports:
      - "${PORT:-3001}:${PORT:-3001}"  # Single port for both frontend and API
    restart: always
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-https://api.cloudflare.com/client/v4}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
      - BACKEND_URL=/api
      - PORT=${PORT:-3001}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3001}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    driver: bridge
