
version: '3.8'

services:
  cloudflare-navigator-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ENDUSERCOMPUTE_FE_CLOUDFLARE
    ports:
      - "8080:8080"  # Expose frontend port
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    driver: bridge
