
version: '3.8'

services:
  cloudflare-navigator-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ENDUSERCOMPUTE_FE_CLOUDFLARE
    ports:
      - "8080:8080"  # Expose frontend port
    environment:
      - API_URL=${API_URL:-/api}
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    driver: bridge
