apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-navigator-config
data:
  FRONTEND_PORT: "8080"
  BACKEND_PORT: "3001"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: wildcard-endusercompute-tls
type: kubernetes.io/tls
data:
  # Replace these with your actual base64 encoded certificate and key
  tls.crt: ${BASE64_ENCODED_CERT}
  tls.key: ${BASE64_ENCODED_KEY}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cloudflare-navigator-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cloudflare-navigator-config
        env:
        - name: BACKEND_SERVICE_URL
          value: "https://api-dns-manager.endusercompute.in/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cloudflare-navigator-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: cloudflare-navigator-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-navigator-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - dns-manager.endusercompute.in
    - api-dns-manager.endusercompute.in
    secretName: wildcard-endusercompute-tls
  rules:
  - host: dns-manager.endusercompute.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8080
  - host: api-dns-manager.endusercompute.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3001
