name: Update K3S Deployment

on:
  workflow_run:
    workflows: ["Build and Push Docker Image with Timestamp Tag"]
    types:
      - completed

jobs:
  update-k3s-yaml:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Get the version
        id: get-version
        run: |
          echo "sha_short=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Checkout application repository
        uses: actions/checkout@v3
        with:
          repository: jsramitkumar/argo-cd-cloudflare-dns  # Replace with your repo B path
          token: ${{ secrets.REPO_PASS }}  # Personal access token with repo scope
          ref: main

      - name: Update image tag in K3S deployment
        run: |
          # Assuming you're using kustomize and updating the image in kustomization.yaml
          # Adjust the following according to your YAML structure
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:sha-${{ steps.get-version.outputs.sha_short }}|g" prod/deployment.yaml
          
          # If you're using a plain K8s manifest:
          # sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:sha-${{ steps.get-version.outputs.sha_short }}|g" path/to/your/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add prod/deployment.yaml
          git commit -m "Update image to sha-${{ steps.get-version.outputs.sha_short }}"
          git push
